services:
    nginx:
        image: nginx:alpine
        container_name: qc-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./server/nginx-ec2.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - qc-api1
            - qc-api2
            - qc-api3
        restart: unless-stopped
        networks:
            - qc-public-net

    qc-api1: &qc-api
        image: ${DOCKERHUB_USERNAME:-lohani01}/quick-chat:server-${VERSION:-v1.0}
        env_file:
            - env/server/.env
        environment:
            - INSTANCE_ID=qc-api1
        restart: unless-stopped
        networks:
            - qc-public-net

    qc-api2:
        <<: *qc-api
        environment:
            - INSTANCE_ID=qc-api2

    qc-api3:
        <<: *qc-api
        environment:
            - INSTANCE_ID=qc-api3

networks:
    qc-public-net:
